"""Base Agentick environment implementing Gymnasium interface."""

from __future__ import annotations

from collections.abc import Callable
from typing import Any

import gymnasium as gym
import numpy as np
from gymnasium import spaces

from agentick.core.actions import ActionSpace, ActionType, compute_action_mask, get_move_delta
from agentick.core.entity import Agent, Entity
from agentick.core.grid import Grid
from agentick.core.renderer import create_renderer
from agentick.core.types import NON_WALKABLE_OBJECTS, CellType, ObjectType


class AgentickEnv(gym.Env):
    """
    Base Agentick environment.

    Implements full Gymnasium API with multi-modal observations and rendering.

    Attributes:
        metadata: Gymnasium metadata with supported render modes
    """

    metadata = {
        "render_modes": [
            "ascii",
            "language",
            "language_structured",
            "rgb_array",
            "human",
            "state_dict",
        ],
        "render_fps": 4,
    }

    def __init__(
        self,
        grid: Grid | None = None,
        render_mode: str = "ascii",
        reward_mode: str = "sparse",
        max_steps: int = 100,
        fast_mode: bool = False,
        **kwargs: Any,
    ):
        """
        Initialize environment.

        Args:
            grid: Initial grid (if None, will be generated by task)
            render_mode: One of the supported render modes:
                ``"ascii"`` — ANSI-colored text grid (default).
                ``"language"`` / ``"language_structured"`` — natural language.
                ``"rgb_array"`` — isometric pixel sprites (512×512, Kenney assets).
                ``"state_dict"`` — structured dict with numpy arrays.
            reward_mode: "sparse", "dense", or "custom"
            max_steps: Maximum steps per episode
            fast_mode: Enable fast mode for state_dict rendering
            **kwargs: Additional task-specific parameters
        """
        super().__init__()

        self.render_mode = render_mode
        self.reward_mode = reward_mode
        self.max_steps = max_steps
        self.fast_mode = fast_mode
        self.kwargs = kwargs

        # Initialize grid (placeholder, will be set by task)
        if grid is None:
            grid = Grid(10, 10)
        self.grid = grid

        # Initialize agent
        self.agent = Agent(
            id="agent_0",
            entity_type="agent",
            position=(1, 1),
        )

        # Entities list (objects, NPCs, etc.)
        self.entities: list[Entity] = []

        # Action space
        self.action_space_obj = ActionSpace()
        self.action_space = self.action_space_obj.gym_space

        # Observation space (depends on render mode)
        self._setup_observation_space()

        # Renderer setup:
        # rgb_array → isometric Kenney sprite renderer (lazy init via _render_isometric)
        # all others → create_renderer factory
        if render_mode == "rgb_array":
            self._iso_renderer = None  # Lazy init
            self.renderer = None  # Will use _render_isometric() directly
        else:
            self._iso_renderer = None
            self.renderer = create_renderer(render_mode, fast_mode=fast_mode)

        # Episode state
        self.step_count = 0
        self.episode_reward = 0.0
        self.done = False

        # RNG for reproducibility
        self.np_random: np.random.Generator = np.random.default_rng()

        # Cache for performance
        self._cached_valid_actions: np.ndarray | None = None
        self._valid_actions_dirty = True

        # Custom reward function
        self.custom_reward_fn: Callable | None = None

    def _setup_observation_space(self) -> None:
        """Setup observation space based on render mode."""
        if self.render_mode == "ascii" or self.render_mode == "language":
            # Text observations - allow printable ASCII with newlines and ANSI codes
            import string

            # Include ESC character (\x1b) for ANSI color codes
            charset = string.printable + "\x1b"
            self.observation_space = spaces.Text(min_length=1, max_length=100000, charset=charset)
        elif self.render_mode == "language_structured":
            # Structured dict observations
            self.observation_space = spaces.Dict(
                {
                    "description": spaces.Text(max_length=1000),
                    "position": spaces.Dict(
                        {
                            "x": spaces.Box(0, self.grid.width, shape=(), dtype=np.int32),
                            "y": spaces.Box(0, self.grid.height, shape=(), dtype=np.int32),
                        }
                    ),
                    "orientation": spaces.Text(max_length=10),
                    "surroundings": spaces.Dict({}),  # Flexible
                    "inventory": spaces.Sequence(spaces.Text(max_length=100)),
                    "energy": spaces.Box(0.0, 1.0, shape=(), dtype=np.float32),
                    "health": spaces.Box(0.0, 1.0, shape=(), dtype=np.float32),
                    "valid_actions": spaces.Sequence(spaces.Text(max_length=20)),
                    "step_count": spaces.Box(0, self.max_steps, shape=(), dtype=np.int32),
                    "max_steps": spaces.Box(0, np.inf, shape=(), dtype=np.int32),
                }
            )
        elif self.render_mode in ("rgb_array", "human"):
            # Isometric pixel observations — fixed 512×512 output
            self.observation_space = spaces.Box(
                low=0, high=255, shape=(512, 512, 3), dtype=np.uint8
            )
        elif self.render_mode == "state_dict":
            # Flexible dict space
            self.observation_space = spaces.Dict({})
        else:
            raise ValueError(f"Unsupported render mode: {self.render_mode}")

    def reset(
        self,
        seed: int | None = None,
        options: dict[str, Any] | None = None,
    ) -> tuple[Any, dict[str, Any]]:
        """
        Reset environment to initial state.

        Args:
            seed: Random seed for reproducibility
            options: Additional reset options

        Returns:
            observation, info
        """
        super().reset(seed=seed)

        if seed is not None:
            self.np_random = np.random.default_rng(seed)

        # Reset episode state
        self.step_count = 0
        self.episode_reward = 0.0
        self.done = False

        # Invalidate caches
        self._valid_actions_dirty = True

        # Task-specific reset (to be implemented by subclasses)
        self._reset_state(seed=seed, options=options)

        # Get initial observation
        obs = self._get_observation()
        info = self._get_info()

        return obs, info

    def step(
        self,
        action: int,
    ) -> tuple[Any, float, bool, bool, dict[str, Any]]:
        """
        Execute one environment step.

        Args:
            action: Action index

        Returns:
            observation, reward, terminated, truncated, info
        """
        if self.done:
            raise RuntimeError("Episode is done. Call reset() to start new episode.")

        self.step_count += 1

        # Save old state for reward computation
        old_state = self._get_state_for_reward()

        # Execute action
        action_type = self.action_space_obj.get_action_type(action)
        self._execute_action(action_type)

        # Invalidate cached valid actions since state changed
        self._valid_actions_dirty = True

        # Get new state
        new_state = self._get_state_for_reward()

        # Compute reward
        reward = self._compute_reward(old_state, action_type, new_state)
        self.episode_reward += reward

        # Check termination
        terminated = self._check_success()
        truncated = self.step_count >= self.max_steps

        self.done = terminated or truncated

        # Get observation and info
        obs = self._get_observation()
        info = self._get_info()
        info["success"] = terminated

        if truncated:
            info["truncated_reason"] = "max_steps_reached"

        return obs, reward, terminated, truncated, info

    def render(self) -> Any | None:
        """
        Render the environment.

        Returns:
            Rendered output (type depends on render_mode)
        """
        if self.render_mode is None:
            return None

        if self.render_mode in ("rgb_array", "rgb_iso"):
            return self._render_isometric()

        info = self._get_info()
        return self.renderer.render(self.grid, self.entities, self.agent, info)

    def _render_isometric(self) -> np.ndarray:
        """Render using the Kenney sprite isometric renderer."""
        if self._iso_renderer is None:
            from agentick.rendering.iso_renderer import IsometricRenderer

            self._iso_renderer = IsometricRenderer(output_size=(512, 512))
        info = self._get_info()
        return self._iso_renderer.render(
            self.grid, self.entities, self.agent, info
        )

    def render_in_mode(self, mode: str) -> Any:
        """Render current state in the given mode (regardless of configured render_mode).

        This enables multimodal agents: the env renders one mode as the primary
        observation, and this method produces additional renderings in other modes.
        """
        if mode in ("rgb_array", "rgb_iso"):
            from agentick.rendering.iso_renderer import IsometricRenderer

            renderer = IsometricRenderer(output_size=(512, 512))
            info = self._get_info()
            return renderer.render(self.grid, self.entities, self.agent, info)
        renderer = create_renderer(mode)
        info = self._get_info()
        return renderer.render(self.grid, self.entities, self.agent, info)

    def close(self) -> None:
        """Clean up resources."""
        pass

    # Methods for agents to access state programmatically

    def get_valid_actions(self) -> np.ndarray:
        """Get binary mask of valid actions."""
        # Use cached result if available
        if not self._valid_actions_dirty and self._cached_valid_actions is not None:
            return self._cached_valid_actions

        # Optimized: avoid expensive np.isin call
        terrain = self.grid.terrain
        walkable = (terrain != CellType.WALL) & (terrain != CellType.HOLE)

        # Account for blocking objects (closed doors, levers, switches)
        objects = self.grid.objects
        blocking = np.zeros_like(walkable)
        for obj_type in NON_WALKABLE_OBJECTS:
            obj_mask = objects == obj_type
            if obj_type == ObjectType.DOOR:
                # Open doors (metadata >= 10) are passable
                obj_mask = obj_mask & (self.grid.metadata < 10)
            blocking |= obj_mask
        walkable = walkable & ~blocking

        mask = compute_action_mask(
            self.action_space_obj,
            self.agent.position,
            walkable,
        )

        # Cache the result
        self._cached_valid_actions = mask
        self._valid_actions_dirty = False

        return mask

    def get_text_observation(self) -> str:
        """Get text observation regardless of render mode."""
        from agentick.core.renderer import LanguageRenderer

        renderer = LanguageRenderer(structured=False)
        info = self._get_info()
        return renderer.render(self.grid, self.entities, self.agent, info)

    def get_pixel_observation(self) -> np.ndarray:
        """Get pixel observation regardless of render mode."""
        return self._render_isometric()

    def get_state_dict(self) -> dict[str, Any]:
        """Get full state dictionary."""
        from agentick.core.renderer import StateDictRenderer

        renderer = StateDictRenderer()
        info = self._get_info()
        return renderer.render(self.grid, self.entities, self.agent, info)

    # Internal methods (to be overridden by tasks)

    def _reset_state(
        self,
        seed: int | None = None,
        options: dict[str, Any] | None = None,
    ) -> None:
        """Reset environment state (to be implemented by subclasses)."""
        pass

    def _execute_action(self, action_type: ActionType) -> None:
        """Execute an action (can be overridden by subclasses)."""
        if action_type == ActionType.NOOP:
            pass
        elif action_type in (
            ActionType.MOVE_UP,
            ActionType.MOVE_DOWN,
            ActionType.MOVE_LEFT,
            ActionType.MOVE_RIGHT,
        ):
            self._move_agent(action_type)
        elif action_type == ActionType.ROTATE_LEFT:
            self.agent.orientation = self.agent.orientation.rotate_left()
        elif action_type == ActionType.ROTATE_RIGHT:
            self.agent.orientation = self.agent.orientation.rotate_right()
        elif action_type == ActionType.MOVE_FORWARD:
            self._move_forward()

    def _move_agent(self, action_type: ActionType) -> None:
        """Move agent based on action."""
        from agentick.core.types import Direction

        _ACTION_DIR = {
            ActionType.MOVE_UP: Direction.NORTH,
            ActionType.MOVE_DOWN: Direction.SOUTH,
            ActionType.MOVE_LEFT: Direction.WEST,
            ActionType.MOVE_RIGHT: Direction.EAST,
        }

        delta = get_move_delta(action_type)
        if delta is None:
            return

        # Update orientation to face movement direction
        if action_type in _ACTION_DIR:
            self.agent.orientation = _ACTION_DIR[action_type]

        dx, dy = delta
        new_pos = (self.agent.position[0] + dx, self.agent.position[1] + dy)

        if self.grid.is_walkable(new_pos) and not self.grid.is_object_blocking(new_pos):
            self.agent.position = new_pos

    def _move_forward(self) -> None:
        """Move agent forward in its facing direction."""
        dx, dy = self.agent.orientation.to_delta()
        new_pos = (self.agent.position[0] + dx, self.agent.position[1] + dy)
        if self.grid.is_walkable(new_pos) and not self.grid.is_object_blocking(new_pos):
            self.agent.position = new_pos

    def _compute_reward(
        self,
        old_state: dict[str, Any],
        action: ActionType,
        new_state: dict[str, Any],
    ) -> float:
        """
        Compute reward for transition.

        To be overridden by subclasses.
        """
        if self.reward_mode == "custom" and self.custom_reward_fn is not None:
            return self.custom_reward_fn(old_state, action, new_state, self._get_info())
        return 0.0

    def _check_success(self) -> bool:
        """Check if task is successfully completed (to be overridden)."""
        return False

    def _get_observation(self) -> Any:
        """Get observation in the configured format."""
        return self.render()

    def _get_info(self) -> dict[str, Any]:
        """Get info dict."""
        valid_mask = self.get_valid_actions()
        valid_action_names = [
            self.action_space_obj.get_action_name(i)
            for i in range(self.action_space_obj.n_actions)
            if valid_mask[i]
        ]

        return {
            "step_count": self.step_count,
            "step": self.step_count,
            "max_steps": self.max_steps,
            "episode_reward": self.episode_reward,
            "valid_actions": valid_action_names,
            "agent_position": self.agent.position,
            "task_name": getattr(self, "_task_name", ""),
        }

    def _get_state_for_reward(self) -> dict[str, Any]:
        """Get state snapshot for reward computation."""
        return {
            "agent_position": self.agent.position,
            "agent_orientation": self.agent.orientation,
            "inventory_size": len(self.agent.inventory),
            "grid_hash": hash(self.grid),
        }
